name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update README.md
      run: python src/main.py > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@github.com'
          git commit -am "bot: update README.md automatically"
          git push
